import '../../features/game/domain/entities/building_definition.dart';

class GameDefinitions {
  static final buildings = [
    const BuildingDefinition(
      id: 'metal_mine',
      name: 'Mine de Métal',
      description: 'Extrait du métal',
      metalCost: 60,
      crystalCost: 15,
      deuteriumCost: 0,
    ),
    const BuildingDefinition(
      id: 'crystal_mine',
      name: 'Mine de Cristal',
      description: 'Extrait du cristal',
      metalCost: 48,
      crystalCost: 24,
      deuteriumCost: 0,
    ),
    const BuildingDefinition(
      id: 'deuterium_synthesizer',
      name: 'Synthétiseur de Deutérium',
      description: 'Produit du deutérium',
      metalCost: 225,
      crystalCost: 75,
      deuteriumCost: 0,
    ),
    const BuildingDefinition(
      id: 'solar_plant',
      name: 'Centrale Solaire',
      description: 'Fournit de l\'énergie',
      metalCost: 75,
      crystalCost: 30,
      deuteriumCost: 0,
    ),
    const BuildingDefinition(
      id: 'robotics_factory',
      name: 'Usine de Robots',
      description: 'Accélère la construction',
      metalCost: 400,
      crystalCost: 120,
      deuteriumCost: 200,
    ),
    const BuildingDefinition(
      id: 'shipyard',
      name: 'Chantier Spatial',
      description: 'Construit des vaisseaux',
      metalCost: 400,
      crystalCost: 200,
      deuteriumCost: 100,
      requirements: ['robotics_factory'],
    ),
  ];

  static final technologies = [
    const BuildingDefinition(
      id: 'energy_tech',
      name: 'Technologie Énergétique',
      description: 'Améliore l\'efficacité énergétique',
      metalCost: 0,
      crystalCost: 800,
      deuteriumCost: 400,
    ),
    const BuildingDefinition(
      id: 'laser_tech',
      name: 'Technologie Laser',
      description: 'Technologie des armes laser',
      metalCost: 200,
      crystalCost: 100,
      deuteriumCost: 0,
    ),
    const BuildingDefinition(
      id: 'ion_tech',
      name: 'Technologie Ionique',
      description: 'Recherche sur les ions',
      metalCost: 1000,
      crystalCost: 300,
      deuteriumCost: 100,
      requirements: ['laser_tech', 'energy_tech'],
    ),
    const BuildingDefinition(
      id: 'hyperspace_tech',
      name: 'Technologie Hyperespace',
      description: 'Voyage spatial rapide',
      metalCost: 0,
      crystalCost: 4000,
      deuteriumCost: 2000,
      requirements: ['energy_tech'],
    ),
    const BuildingDefinition(
      id: 'plasma_tech',
      name: 'Technologie Plasma',
      description: 'Armes au plasma avancées',
      metalCost: 2000,
      crystalCost: 4000,
      deuteriumCost: 1000,
      requirements: ['laser_tech', 'ion_tech'],
    ),
    const BuildingDefinition(
      id: 'espionage_tech',
      name: 'Technologie Espionnage',
      description: 'Espionnez vos adversaires',
      metalCost: 200,
      crystalCost: 1000,
      deuteriumCost: 200,
    ),
    const BuildingDefinition(
      id: 'computer_tech',
      name: 'Technologie Informatique',
      description: 'Gestion avancée des flottes',
      metalCost: 0,
      crystalCost: 400,
      deuteriumCost: 600,
    ),
    const BuildingDefinition(
      id: 'astrophysics',
      name: 'Astrophysique',
      description: 'Colonisez plus de planètes',
      metalCost: 4000,
      crystalCost: 8000,
      deuteriumCost: 4000,
      requirements: ['espionage_tech', 'computer_tech'],
    ),
    const BuildingDefinition(
      id: 'intergalactic_network',
      name: 'Réseau Intergalactique',
      description: 'Communication instantanée',
      metalCost: 240000,
      crystalCost: 400000,
      deuteriumCost: 160000,
      requirements: ['computer_tech', 'hyperspace_tech'],
    ),
  ];

  static final diplomacyTechs = [
    const BuildingDefinition(
      id: 'communism',
      name: '☭ Communisme Spatial',
      description: 'Redistribution des ressources : +15% production de métal',
      metalCost: 5000,
      crystalCost: 2500,
      deuteriumCost: 1000,
    ),
    const BuildingDefinition(
      id: 'capitalism',
      name: '💰 Capitalisme Galactique',
      description: 'Efficacité du marché : -10% coûts de construction',
      metalCost: 3000,
      crystalCost: 5000,
      deuteriumCost: 2000,
    ),
    const BuildingDefinition(
      id: 'trump_action',
      name: '🏢 Action de Trump',
      description:
          'Construisez le mur spatial ! +20% production de cristal, +10% énergie',
      metalCost: 10000,
      crystalCost: 5000,
      deuteriumCost: 3000,
      requirements: ['capitalism'],
    ),
    const BuildingDefinition(
      id: 'french_revolution',
      name: '🥖 Révolution Française',
      description: 'Liberté, Égalité, Fraternité : +25% vitesse de recherche',
      metalCost: 7500,
      crystalCost: 7500,
      deuteriumCost: 5000,
    ),
    const BuildingDefinition(
      id: 'pizza_party',
      name: '🍕 Pizza Party Universelle',
      description:
          'Moral des troupes : Production +10% de toutes les ressources',
      metalCost: 2000,
      crystalCost: 1000,
      deuteriumCost: 500,
    ),
    const BuildingDefinition(
      id: 'intergalactic_memes',
      name: '😂 Memes Intergalactiques',
      description: 'Guerre psychologique : -15% coûts de recherche',
      metalCost: 6969,
      crystalCost: 4200,
      deuteriumCost: 1337,
      requirements: ['pizza_party'],
    ),
    const BuildingDefinition(
      id: 'space_coffee',
      name: '☕ Café Spatial Premium',
      description: 'Productivité maximale : +30% vitesse de construction',
      metalCost: 8000,
      crystalCost: 6000,
      deuteriumCost: 4000,
      requirements: ['pizza_party'],
    ),
    const BuildingDefinition(
      id: 'alien_alliance',
      name: '👽 Alliance Extraterrestre',
      description: 'Technologies alien : +50% production d\'énergie',
      metalCost: 15000,
      crystalCost: 20000,
      deuteriumCost: 10000,
      requirements: ['intergalactic_memes', 'trump_action'],
    ),
  ];
}
