import 'package:les_architectes_cosmiques/features/building/domain/entities/building.dart';
import 'package:les_architectes_cosmiques/features/planet/domain/entities/planet.dart';
import 'package:les_architectes_cosmiques/features/planet/domain/entities/ressource.dart';

import '../../features/planet/domain/entities/planet_name.dart';

final defaultPlanets = [
  Planet(
    id: 1,
    userId: 1,
    name: PlanetName.mercure,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 1,
        type: BuildingType.mine_metal,
        planetId: '1',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 2,
        type: BuildingType.usine,
        planetId: '1',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 3,
        type: BuildingType.laboratoire,
        planetId: '1',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 4,
        type: BuildingType.centrale,
        planetId: '1',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 39,
        type: BuildingType.mine_cristal,
        planetId: '1',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 40,
        type: BuildingType.mine_deuterium,
        planetId: '1',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 2,
    userId: 1,
    name: PlanetName.venus,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 5,
        type: BuildingType.mine_metal,
        planetId: '2',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 6,
        type: BuildingType.usine,
        planetId: '2',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 7,
        type: BuildingType.laboratoire,
        planetId: '2',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 8,
        type: BuildingType.centrale,
        planetId: '2',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 41,
        type: BuildingType.mine_cristal,
        planetId: '2',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 42,
        type: BuildingType.mine_deuterium,
        planetId: '2',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 3,
    userId: 1,
    name: PlanetName.terre,
    politicalRegime: 'Démocratie galactique',
    resources: [
      const Resource(id: 1, planetId: 1, type: 'Métal', quantity: 1500.5),
      const Resource(id: 2, planetId: 1, type: 'Cristal', quantity: 870.0),
      const Resource(id: 3, planetId: 1, type: 'Deutérium', quantity: 5000.0),
    ],
    isColonized: true,
    buildings: [
      Building(
        id: 9,
        type: BuildingType.mine_metal,
        planetId: '3',
        niveau: 2,
        energieCost: 10,
      ),
      Building(
        id: 10,
        type: BuildingType.usine,
        planetId: '3',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 11,
        type: BuildingType.laboratoire,
        planetId: '3',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 12,
        type: BuildingType.centrale,
        planetId: '3',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 37,
        type: BuildingType.mine_cristal,
        planetId: '3',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 38,
        type: BuildingType.mine_deuterium,
        planetId: '3',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 4,
    userId: 1,
    name: PlanetName.mars,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 13,
        type: BuildingType.mine_metal,
        planetId: '4',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 14,
        type: BuildingType.usine,
        planetId: '4',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 15,
        type: BuildingType.laboratoire,
        planetId: '4',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 16,
        type: BuildingType.centrale,
        planetId: '4',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 43,
        type: BuildingType.mine_cristal,
        planetId: '4',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 44,
        type: BuildingType.mine_deuterium,
        planetId: '4',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 5,
    userId: 1,
    name: PlanetName.jupiter,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 17,
        type: BuildingType.mine_metal,
        planetId: '5',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 18,
        type: BuildingType.usine,
        planetId: '5',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 19,
        type: BuildingType.laboratoire,
        planetId: '5',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 20,
        type: BuildingType.centrale,
        planetId: '5',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 45,
        type: BuildingType.mine_cristal,
        planetId: '5',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 46,
        type: BuildingType.mine_deuterium,
        planetId: '5',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 6,
    userId: 1,
    name: PlanetName.saturne,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 21,
        type: BuildingType.mine_metal,
        planetId: '6',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 22,
        type: BuildingType.usine,
        planetId: '6',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 23,
        type: BuildingType.laboratoire,
        planetId: '6',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 24,
        type: BuildingType.centrale,
        planetId: '6',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 47,
        type: BuildingType.mine_cristal,
        planetId: '6',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 48,
        type: BuildingType.mine_deuterium,
        planetId: '6',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 7,
    userId: 1,
    name: PlanetName.uranus,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 25,
        type: BuildingType.mine_metal,
        planetId: '7',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 26,
        type: BuildingType.usine,
        planetId: '7',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 27,
        type: BuildingType.laboratoire,
        planetId: '7',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 28,
        type: BuildingType.centrale,
        planetId: '7',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 49,
        type: BuildingType.mine_cristal,
        planetId: '7',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 50,
        type: BuildingType.mine_deuterium,
        planetId: '7',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 8,
    userId: 1,
    name: PlanetName.neptune,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 29,
        type: BuildingType.mine_metal,
        planetId: '8',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 30,
        type: BuildingType.usine,
        planetId: '8',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 31,
        type: BuildingType.laboratoire,
        planetId: '8',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 32,
        type: BuildingType.centrale,
        planetId: '8',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 51,
        type: BuildingType.mine_cristal,
        planetId: '8',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 52,
        type: BuildingType.mine_deuterium,
        planetId: '8',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
  Planet(
    id: 9,
    userId: 1,
    name: PlanetName.pluton,
    politicalRegime: '',
    resources: [],
    isColonized: false,
    buildings: [
      Building(
        id: 33,
        type: BuildingType.mine_metal,
        planetId: '9',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 34,
        type: BuildingType.usine,
        planetId: '9',
        niveau: 0,
        energieCost: 15,
      ),
      Building(
        id: 35,
        type: BuildingType.laboratoire,
        planetId: '9',
        niveau: 0,
        energieCost: 25,
      ),
      Building(
        id: 36,
        type: BuildingType.centrale,
        planetId: '9',
        niveau: 0,
        energieCost: 30,
      ),
      Building(
        id: 53,
        type: BuildingType.mine_cristal,
        planetId: '9',
        niveau: 0,
        energieCost: 10,
      ),
      Building(
        id: 54,
        type: BuildingType.mine_deuterium,
        planetId: '9',
        niveau: 0,
        energieCost: 10,
      ),
    ],
  ),
];
